version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development  # Ensure this is set to a standard value

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: cpq-user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cpqDb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
